name: engineer_registration_app
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - apps/admin_app/dart_backend
  - apps/corporate_user_app/dart_backend
  - apps/fmjs/dart_backend
  - apps/individual_user_app/dart_backend
  - apps/job_description/dart_backend
  - shared/domain_models
  - shared/common_logic
  - shared/common_backend
  - shared/domain_logic/heatmap_engine
  - infrastructure/firebase/functions

dev_dependencies:
  melos: ^7.3.0

melos:
  scripts:
    analyze:
      run: melos exec -- dart analyze
      description: Run static analysis on all Dart packages
    test:
      run: |
        melos exec -- "[ -d test ] && ( (grep -q 'sdk: flutter' pubspec.yaml && flutter test) || dart test ) || echo 'No tests found, skipping...'"
      description: Run tests for all Dart packages (smartly switching between dart/flutter test)
    format:
      run: melos exec -- dart format .
      description: Format all Dart code
    clean:
      run: melos clean
      description: Clean all Dart packages
    get:
      run: melos exec -- dart pub get
      description: Get dependencies for all Dart packages
    upgrade:
      run: melos exec -- dart pub upgrade
      description: Upgrade dependencies for all Dart packages
  command:
    bootstrap:
      runPubGetInParallel: true
